-- Create table
create table sa_gasto
(
  ano_eje                       NUMBER,
--  mes_eje                       NUMBER,
  nivel_gobierno                VARCHAR2(2),
--  nivel_gobierno_nombre         VARCHAR2(30),
  sector                        NUMBER,
  sector_nombre                 VARCHAR2(50),
  pliego                        NUMBER,
  pliego_nombre                 VARCHAR2(128),
  sec_ejec                      NUMBER,
  ejecutora                     NUMBER,
  ejecutora_nombre              VARCHAR2(100),
  departamento_ejecutora        NUMBER,
  departamento_ejecutora_nombre VARCHAR2(48),
  provincia_ejecutora           NUMBER,
  provincia_ejecutora_nombre    VARCHAR2(64),
  distrito_ejecutora            NUMBER,
  distrito_ejecutora_nombre     VARCHAR2(64),
  sec_func                      NUMBER,
  programa_ppto                 NUMBER,
  programa_ppto_nombre          VARCHAR2(128),
  tipo_act_proy                 NUMBER,
  tipo_act_proy_nombre          VARCHAR2(16),
  producto_proyecto             NUMBER,
  producto_proyecto_nombre      VARCHAR2(512),
  actividad_accion_obra         NUMBER,
  actividad_accion_obra_nombre  VARCHAR2(200),
  funcion                       NUMBER,
  funcion_nombre                VARCHAR2(64),
  division_funcional            NUMBER,
  division_funcional_nombre     VARCHAR2(200),
  grupo_funcional               NUMBER,
  grupo_funcional_nombre        VARCHAR2(200),
  meta                          NUMBER,
  finalidad                     NUMBER,
  meta_nombre                   VARCHAR2(512),
  departamento_meta             NUMBER,
  departamento_meta_nombre      VARCHAR2(48),
  fuente_financiamiento         NUMBER,
  fuente_financiamiento_nombre  VARCHAR2(64),
  rubro                         NUMBER,
  rubro_nombre                  VARCHAR2(128),
  tipo_recurso                  VARCHAR2(8),
  tipo_recurso_nombre           VARCHAR2(128),
  categoria_gasto               NUMBER,
  categoria_gasto_nombre        VARCHAR2(32),
  tipo_transaccion              NUMBER,
  generica                      NUMBER,
  generica_nombre               VARCHAR2(64),
  subgenerica                   NUMBER,
  subgenerica_nombre            VARCHAR2(64),
  subgenerica_det               NUMBER,
  subgenerica_det_nombre        VARCHAR2(64),
  especifica                    NUMBER,
  especifica_nombre             VARCHAR2(128),
  especifica_det                NUMBER,
  especifica_det_nombre         VARCHAR2(200),
  monto_pia                     FLOAT,
  monto_pim                     float,
  monto_certificado             float,
  monto_comprometido_anual      float,
  monto_comprometido            float,
  monto_devengado               float,
  monto_girado                  float,
  fecha_creacion                DATE default sysdate,
  usuario_creacion              VARCHAR2(30) default user
)
NOPARALLEL
NOLOGGING
PARTITION BY RANGE (ano_eje) (
    PARTITION p_2012 VALUES LESS THAN (2013),
    PARTITION p_2013 VALUES LESS THAN (2014),
    PARTITION p_2014 VALUES LESS THAN (2015),
    PARTITION p_2015 VALUES LESS THAN (2016),
    PARTITION p_2016 VALUES LESS THAN (2017),
    PARTITION p_2017 VALUES LESS THAN (2018),
    PARTITION p_2018 VALUES LESS THAN (2019),
    PARTITION p_2019 VALUES LESS THAN (2020),
    PARTITION p_2020 VALUES LESS THAN (2021),
    PARTITION p_2021 VALUES LESS THAN (2022),
    PARTITION p_2022 VALUES LESS THAN (2023),
    PARTITION p_2023 VALUES LESS THAN (2024),
    PARTITION p_2024 VALUES LESS THAN (2025),
    PARTITION pmax VALUES LESS THAN (MAXVALUE)
);